sonar.projectKey=czerniak1337_PASIR_Wiktor_Czerniak_Lab14
sonar.organization=czerniak1337
sonar.host.url=https://sonarcloud.io

sonar.sources=BudgetApp/backend/src/main, BudgetApp/frontend/src

sonar.java.binaries=BudgetApp/backend/target/classes

sonar.exclusions=**/*.zip,**/node_modules/**,**/dist/**