name: Build

on:
  push:
    branches:
      - lab14
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backend
        working-directory: BudgetApp/backend
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}